### PR TITLE
Runtime: Make const/non-const getters have the same name

### PR DESCRIPTION
**Pull request by lioncash**
Makes for a more consistent interface, as getters won't have different names to remember based off whether or not they're const qualified.

---
This change is [Reviewable](https://reviewable.io/reviews/axiodl/urde/42)

### CODE REVIEW

**Comment by Antidote** [comment]
This would break our goal of historically accurate function names, while it would normally be a good idea to do what you propose, it goes against a tenant we put in place at the beginning of the project: Faithfully recreating function names where possible.

**Comment by lioncash** [comment]
Is that a particularly good tenet enforce in the interface itself rather than via documentation though? This can lead to cases (in both generic, and non-generic code) where code can fail to compile where it otherwise wouldn't. 

For example:

```cpp
void SomeClass::SomeFunction(SomeObject& ref) {
  // Assume nothing actually modifies ref, but only queries state.
  // allowing it to be changed into a const reference to better signal
  // intentions.

  auto& ref = ref.ThingNC();

  // ...
}
```

if this is changed to:

```cpp
void SomeClass::SomeFunction(const SomeObject& ref) {
  const auto& ref.ThingNC();

  // ...
}
```

then this code will break due to the naming difference and require checking the interface for a differently named function that does the exact same thing; essentially creating more work that could be avoided.

I guess I'm not quite sure I understand why such a tenet is in place. What gain comes from it that couldn't be rectified with documentation of the original classes? (particularly for trivial getter functions⁠—I can understand the argument for functions that do meaningful behavior)

**Comment by Antidote** [comment]
You raise a good point about Getters/Setters, we put that tenet in place because we wanted to be as faithful as possible, but we can't let that affect code quality on small details that can be expounded upon via documentation, I'm going to go ahead and merge this.

**Comment by lioncash** [comment]
Alright, sounds good! Thanks for explaining 👌

**Pull request merged**
